//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ralwey.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RalweysEntities : DbContext
    {
        public RalweysEntities()
            : base("name=RalweysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aboutt> Aboutt { get; set; }
        public virtual DbSet<Categoru> Categoru { get; set; }
        public virtual DbSet<our_skill> our_skill { get; set; }
        public virtual DbSet<Partners> Partners { get; set; }
        public virtual DbSet<pay_value> pay_value { get; set; }
        public virtual DbSet<pricing_plans> pricing_plans { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<Slider> Slider { get; set; }
        public virtual DbSet<Statistic> Statistic { get; set; }
        public virtual DbSet<Terms> Terms { get; set; }
        public virtual DbSet<Testimonals> Testimonals { get; set; }
        public virtual DbSet<Work> Work { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public object DriverRegs { get; internal set; }
    }
}
