//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ralwey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public int id { get; set; }
        public string photo { get; set; }
        public string link { get; set; }
    }
}
