//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ralwey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay_value
    {
        public int id { get; set; }
        public string name { get; set; }
        public int orderby { get; set; }
        public int pricing_plans_id { get; set; }
    
        public virtual pricing_plans pricing_plans { get; set; }
    }
}
